name: FizzBuzz Testing

on: [push, pull_request]

jobs:
  test-nodejs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run Test
      run: node fizzbuzz.js | tr -d '\r' > /tmp/js.txt

    - name: Setup Check File
      run: cat fizzbuzz.txt | tr -d '\r' > /tmp/check.txt

    - name: Compare output
      run: diff -i /tmp/js.txt /tmp/check.txt
